[[headers]]
  for = "/*"
[headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "*"

# [[redirects]]  <--- 删除或注释掉这一整块
#  from = "/*"
#  to = "/.netlify/functions/proxy"
#  status = 200
#  force = true

# 添加 Edge Function 配置
[[edge_functions]]
  # path 定义了哪些请求路径会触发这个 Edge Function
  # "/*" 表示所有路径
  path = "/*"
  # function 指定了要运行的 Edge Function 的名字
  # 这个名字通常是 `netlify/edge-functions/` 目录下不带扩展名的文件名
  function = "proxy"
